apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
        - name: menu-service
          image: menu-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DOCKER_COMPOSE_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://menu-db:5432/menu_db
            - name: SPRING_DATASOURCE_USERNAME
              value: menu
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu-service
  ports:
    - port: 8082
      targetPort: 8082